---
# tasks file for ecs-agent
- name: gather instance facts
  ec2_instance_facts:
    region: us-east-1
    filters:
      "tag:Name": "{{instance_name}}"
      "instance-state-name": running
#      "tag:Environment": "{{env}}"
  register: node

- name: set instance name
  set_fact:
    node_ip: "{{ node.instances[0].network_interfaces[0].private_ip_address }}"

- name: create ecs directory
  file:
    path: "{{item}}"
    state: directory
  loop:
    - "/etc/ecs"
    - "/var/log/ecs"
    - "/var/lib/ecs/data"

- name: copy file ecs.config to /etc/ecs/ecs.config
  template:
    src: ecs.config.j2
    dest: /etc/ecs/ecs.config
